# -*- coding: utf-8 -*-
"""Crop_selector_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYyv_bF54MX_YMWvIkIKe2aKlJyO15dL

# Imports
"""

import numpy as np
import pandas as pd
import xgboost as xgb
import joblib

"""### Dataset"""

dataset= pd.read_csv("Crop_recommendation.csv")

dataset.head()

"""## Data preprocessing

"""

x = dataset.drop("label", axis=1)
y = dataset["label"]


print(x)

x.shape
y.shape

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size =0.2,random_state=1)

from sklearn.metrics import accuracy_score, mean_squared_error
model = xgb.XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    random_state=1
)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)


from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

test_sample = pd.DataFrame([{
    "N": 10,
    "P": 82,
    "K": 23,
    "temperature": 50.87,
    "humidity": 82.00,
    "ph": 2.5,
    "rainfall": 102.93
}])

prediction = model.predict(test_sample)

print("Recommended crop:", prediction[0])

probs = model.predict_proba(test_sample)

top3_idx = np.argsort(probs[0])[-3:][::-1]

print("Top 3 crops:")
for i in top3_idx:
    print(le.inverse_transform([i])[0], probs[0][i])

joblib.dump(model, "crop_model.pkl")

joblib.dump(le, "label_encoder.pkl")