"""add market intelligence tables

Revision ID: 0db7eddc5a8a
Revises: 
Create Date: 2026-04-26 19:57:27.828285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0db7eddc5a8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandi_price_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('modal_price', sa.Float(), nullable=True),
    sa.Column('arrival_date', sa.String(length=50), nullable=True),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_price_data_commodity'), 'mandi_price_data', ['commodity'], unique=False)
    op.create_index(op.f('ix_mandi_price_data_market'), 'mandi_price_data', ['market'], unique=False)
    op.create_index(op.f('ix_mandi_price_data_recorded_at'), 'mandi_price_data', ['recorded_at'], unique=False)
    op.create_table('market_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('best_market', sa.String(length=100), nullable=True),
    sa.Column('best_price', sa.Float(), nullable=True),
    sa.Column('forecast_trend', sa.String(length=20), nullable=True),
    sa.Column('predicted_price', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_recommendations_id'), 'market_recommendations', ['id'], unique=False)

    op.alter_column('soil_data', 'alerts',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='alerts::json')
    op.alter_column('soil_data', 'recommendations',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='recommendations::json')
    op.create_index(op.f('ix_soil_data_recorded_at'), 'soil_data', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soil_data_recorded_at'), table_name='soil_data')
    op.alter_column('soil_data', 'recommendations',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using='recommendations::text')
    op.alter_column('soil_data', 'alerts',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using='alerts::text')

    op.drop_index(op.f('ix_market_recommendations_id'), table_name='market_recommendations')
    op.drop_table('market_recommendations')
    op.drop_index(op.f('ix_mandi_price_data_recorded_at'), table_name='mandi_price_data')
    op.drop_index(op.f('ix_mandi_price_data_market'), table_name='mandi_price_data')
    op.drop_index(op.f('ix_mandi_price_data_commodity'), table_name='mandi_price_data')
    op.drop_table('mandi_price_data')
    op.drop_table('users')
    # ### end Alembic commands ###
